import { ArrowLeft } from 'lucide-react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Research-Agent',
  description: 'Terms of Service for Research-Agent',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-zinc-950">
      <div className="max-w-3xl mx-auto px-4 py-8">
        <Link
          href="/chat"
          className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-zinc-300 mb-6"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>

        <h1 className="text-2xl font-bold text-white mb-2">
          RESEARCH-AGENT TERMS OF SERVICE
        </h1>
        <p className="text-zinc-400 mb-8">Last updated: 13 May 2025</p>

        <div className="space-y-6">
          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              1. ACCEPTANCE
            </h2>
            <p className="text-zinc-300">
              By creating an account, purchasing a subscription, or otherwise
              using Research-Agent (the &quot;Service&quot;) you—hereafter
              &quot;User&quot; or &quot;you&quot;—agree to these Terms of
              Service (&quot;Terms&quot;) and our Privacy Policy. If you do not
              agree, do not use the Service.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              2. DESCRIPTION OF THE SERVICE
            </h2>
            <p className="text-zinc-300">
              The Service retrieves biomedical literature from PubMed Central,
              embeds the text, and uses large-language models to generate
              summaries and chat responses (collectively &quot;Outputs&quot;).
              Outputs are autogenerated and may contain inaccuracies or outdated
              information.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              3. NO MEDICAL OR PROFESSIONAL ADVICE
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-zinc-300">
              <li>
                Informational use only. Outputs are provided for educational and
                research purposes.
              </li>
              <li>
                No doctor–patient relationship. The Service is not a substitute
                for professional medical advice, diagnosis, or treatment.
              </li>
              <li>
                Seek a clinician. Always consult a qualified health-care
                provider about a medical condition. In an emergency dial 911
                (U.S.) or your local emergency number.
              </li>
              <li>No pharmacy or legal advice.</li>
            </ul>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              4. ELIGIBILITY & ACCOUNTS
            </h2>
            <p className="text-zinc-300">
              You must be at least 18 years old and capable of forming a binding
              contract. You are responsible for safeguarding your credentials
              and all activity under your account.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              5. SUBSCRIPTIONS & BILLING
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-zinc-300">
              <li>
                Trial & refunds. Unless stated otherwise, payments are
                non-refundable and prorated partial-month refunds are not
                offered.
              </li>
              <li>
                Cancellation. Cancel anytime from the &quot;Billing&quot; page;
                access continues until the end of the paid term.
              </li>
            </ul>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              6. ACCEPTABLE USE
            </h2>
            <p className="text-zinc-300 mb-4">You agree not to:</p>
            <div className="space-y-4">
              <div>
                <p className="font-semibold text-zinc-300">PHI / HIPAA data</p>
                <p className="text-zinc-400">
                  Upload a patient&apos;s MRN, full date of birth, or medical
                  images.
                </p>
              </div>
              <div>
                <p className="font-semibold text-zinc-300">
                  Clinical decision support
                </p>
                <p className="text-zinc-400">
                  Use Outputs to prescribe, dose, diagnose, triage, or otherwise
                  manage individual patient care.
                </p>
              </div>
              <div>
                <p className="font-semibold text-zinc-300">
                  Illegal or infringing acts
                </p>
                <p className="text-zinc-400">
                  Violate export-control laws, OFAC sanctions, or third-party
                  IP.
                </p>
              </div>
              <div>
                <p className="font-semibold text-zinc-300">Security abuse</p>
                <p className="text-zinc-400">
                  Probe, scan, or test the Service without consent; distribute
                  malware.
                </p>
              </div>
            </div>
            <p className="text-zinc-300 mt-4">
              We reserve the right to suspend or terminate accounts that breach
              this policy.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              7. INTELLECTUAL PROPERTY
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-zinc-300">
              <li>
                Service IP. We (or our licensors) own all right, title, and
                interest in the Service, including code, models, UI, and
                trademarks.
              </li>
              <li>
                User Content. You retain all rights to text you input
                (&quot;User Content&quot;). You grant us a worldwide,
                royalty-free license to process and store User Content for the
                purpose of operating and improving the Service.
              </li>
              <li>
                Outputs. Subject to these Terms you may use Outputs for any
                lawful purpose, including commercial, but you acknowledge that
                (a) Outputs may be similar to content provided to other users,
                and (b) we do not grant any warranty of non-infringement.
              </li>
            </ul>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              8. THIRD-PARTY SERVICES & MODELS
            </h2>
            <p className="text-zinc-300">
              Outputs may be generated via OpenAI, Google AI, Anthropic, or
              other third-party LLM vendors. Use of the Service constitutes
              acceptance of those vendors&apos; terms.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              9. DISCLAIMERS
            </h2>
            <p className="text-zinc-300">
              THE SERVICE AND ALL OUTPUTS ARE PROVIDED &quot;AS IS&quot; AND
              &quot;AS AVAILABLE.&quot; TO THE MAXIMUM EXTENT PERMITTED BY LAW,
              WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
              ACCURACY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              10. LIMITATION OF LIABILITY
            </h2>
            <p className="text-zinc-300">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, RESEARCH-AGENT AND ITS
              SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL,
              INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOST
              PROFITS, DATA, GOODWILL, OR BUSINESS INTERRUPTION, EVEN IF ADVISED
              OF THE POSSIBILITY. OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO
              THE SERVICE SHALL NOT EXCEED USD $100 OR THE AMOUNT YOU PAID US IN
              THE 12 MONTHS BEFORE THE CLAIM, WHICHEVER IS GREATER.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              11. INDEMNIFICATION
            </h2>
            <p className="text-zinc-300">
              You will defend, indemnify, and hold harmless Research-Agent, its
              directors, and employees from any claims arising out of (a) your
              use of the Service, (b) User Content, or (c) your breach of these
              Terms.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              12. GOVERNING LAW & DISPUTE RESOLUTION
            </h2>
            <p className="text-zinc-300">
              These Terms are governed by the laws of the State of Delaware,
              USA, without regard to conflict-of-laws principles.
            </p>
            <p className="text-zinc-300 mt-2">
              <strong>Binding Arbitration & Class-Action Waiver.</strong> Any
              dispute shall be resolved by confidential, final, and binding
              arbitration administered by the American Arbitration Association
              in Wilmington, Delaware, under its Commercial Rules. You and we
              waive any right to participate in a class or representative
              action.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              13. EXPORT CONTROLS & SANCTIONS
            </h2>
            <p className="text-zinc-300">
              You may not use the Service if you are located in, or a resident
              of, a country or region subject to comprehensive U.S. sanctions,
              or if you are on any U.S. government restricted-party list.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              14. CHANGES TO TERMS
            </h2>
            <p className="text-zinc-300">
              We may revise these Terms at any time. Material changes will be
              posted at least 7 days in advance. Continued use after the
              effective date constitutes acceptance.
            </p>
          </section>

          <section className="bg-zinc-900/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-white mb-4">
              15. TERMINATION
            </h2>
            <p className="text-zinc-300">
              We may suspend or terminate access at any time for violation of
              these Terms. Sections 3, 7-12, and 15 survive termination.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
