services:
  - type: web
    name: research-agent
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build -w api && npm run build -w worker
    startCommand: node api/dist/api/src/index.js & node worker/dist/worker/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here
