services:
  - type: web
    name: research-agent
    env: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm install -w api --include=dev && npm install -w worker --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here
