services:
  - type: web
    name: research-agent
    env: node
    rootDir: backend
    buildCommand: npm install && npm install -w api && npm install -w worker && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here
