version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm', 'run', 'dev:api']
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
      - ./libs:/app/libs
      - /app/lib
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm', 'run', 'dev:worker']
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - ./worker:/app/worker
      - /app/worker/node_modules
      - ./libs:/app/libs
      - /app/libs/node_modules
