version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672' # RabbitMQ protocol
      - '15672:15672' # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://admin:secret@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      RABBITMQ_URL: amqp://admin:secret@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - rabbitmq

volumes:
  rabbitmq-data:
